export { default as logo } from "./2 белый фон 1.png";
export { default as whatsapp } from "./whatsapp (1) 1.png";
export { default as phoneCall } from "./phone-call 2.png";
export { default as spain } from "./spain (1) 1.png";
export { default as russia } from "./russia 1.png";
export { default as menyuBar } from "./menu 1.png";
export { default as close } from "./close 1.png";
export { default as insta } from "./instagram (1) 1.png";
export { default as insta2 } from "./instagram (2) 1.png";
export { default as facebook } from "./facebook (3) 1.png";
export { default as homeHead } from "./tom-wheatley-QiJ-jdv-6t0-unsplash 1.png";
export { default as newsHead } from "./006_PEDROJAEN_DJI_0815 2.png";
export { default as secondayHead } from "./006_PEDROJAEN_DJI_0815 2 (1).png";
export { default as rentHead } from "./006_PEDROJAEN_DJI_0815 2 (2).png";
export { default as lantPlotsHead } from "./006_PEDROJAEN_DJI_0815 2 (3).png";
export { default as aboutBgImg } from "./Rectangle 40.png";
export { default as aboutImg } from "./IMG_4948 3.png";
export { default as objektImg1 } from "./3 1.png";
export { default as objektImg2 } from "./BBV 1.png";
export { default as objektImg3 } from "./Corner view 1.png";
export { default as objektImg4 } from "./006_PEDROJAEN_DJI_0815 1.png";
export { default as ekaterinaImg1 } from "./image 1.png";
export { default as ekaterinaImg2 } from "./image 2.png";
export { default as ekaterinaImg3 } from "./image 3.png";
export { default as ekaterinaImg4 } from "./image 4.png";
export { default as ekaterinaImg5 } from "./image 5.png";
export { default as ekaterinaImg6 } from "./image 6.png";
export { default as ekaterinaImg7 } from "./image 7.png";
export { default as ekaterinaImg8 } from "./image 8.png";
export { default as ekaterinaImg9 } from "./image 9.png";
export { default as ekaterinaImg } from "./DSCF5637ed 1.png";
export { default as foooterLogo } from "./1 белый 1.png";
export { default as fooIns } from "./footerInsta.png";
export { default as fooFas } from "./footerFac.png";
export { default as building1 } from "./building (1).png";
export { default as building2 } from "./building (2).png";
export { default as building3 } from "./building (3).png";
export { default as building4 } from "./building (4).png";
export { default as building5 } from "./building (5).png";
export { default as building6 } from "./building (6).png";
export { default as building7 } from "./building (7).png";
export { default as building8 } from "./building (8).png";
export { default as building9 } from "./building (9).png";
export { default as building10 } from "./building (10).png";
export { default as building11 } from "./building (11).png";
export { default as searchImg } from "./searching-magnifying-glass 1.png";
export { default as nextTop } from "./next (2) 2.png";
export { default as nextSlideBtn1 } from "./next (1) 2.png";
export { default as nextSlideBtn2 } from "./next (1) 1.png";
